# Generated by Django 3.2 on 2021-04-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(max_length=500, null=True)),
                ('messages', models.CharField(max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.IntegerField(null=True)),
                ('message_id', models.IntegerField(null=True)),
                ('message_text', models.CharField(max_length=5000, null=True)),
                ('message_images', models.CharField(max_length=5000, null=True)),
            ],
        ),
    ]
