# Generated by Django 3.2 on 2021-04-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socketio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.IntegerField(auto_created=True, null=True),
        ),
    ]
