# Generated by Django 3.2 on 2021-04-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socketio_app', '0002_alter_message_message_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_images',
        ),
        migrations.AddField(
            model_name='message',
            name='images',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
