# Generated by Django 3.2 on 2021-04-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socketio_app', '0003_auto_20210420_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
