# Generated by Django 3.2 on 2021-04-10 16:22

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('lookingForAJob', models.BooleanField(null=True)),
                ('lookingForAJobDescription', models.CharField(max_length=500, null=True)),
                ('fullName', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('contacts', models.CharField(max_length=500, null=True)),
                ('photos', models.CharField(max_length=5000, null=True)),
                ('followers', models.CharField(default='', max_length=5000, null=True)),
                ('friends', models.CharField(default='', max_length=5000, null=True)),
                ('aboutMe', models.CharField(default='', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.IntegerField()),
                ('author_photo', models.CharField(max_length=5000, null=True)),
                ('image', models.CharField(max_length=5000, null=True)),
                ('post_text', models.CharField(max_length=5000, null=True)),
                ('likes', models.CharField(max_length=5000, null=True)),
                ('comments', models.CharField(max_length=5000, null=True)),
                ('reposts', models.CharField(max_length=5000, null=True)),
            ],
        ),
    ]
