# Generated by Django 3.2 on 2021-04-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='token',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
