# Generated by Django 3.2 on 2021-04-20 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_myuser_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_text',
            new_name='text',
        ),
    ]
