# Generated by Django 3.2 on 2021-04-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_page',
            field=models.IntegerField(null=True),
        ),
    ]
